### ISSUE TITLE
Issue on page /elements/oneMKL/source/domains/lapack/lapack.html

### ISSUE THREAD

**Issue by jakub-homola** [oneapi-src/oneAPI-spec#470]
Hi,

Are all the matrices in the LAPACK domain of oneMKL assumed to be row-major or column-major?

It seems they are assumed to be column-major, but I could not find that information anywhere on the webpage, nor there are any `oneapi::mkl::layout` parameters to the functions. Right now I am mainly concerned about `potrf` and `trtrs`, but knowing that information for the whole LAPACK would be great.

Could you please redirect me to where I can find that information, or add it to the spec/docs?

The version of the spec I am seeing is 1.2-rev-1

**Comment by mmeterel** [comment]
Assigning to @sknepper

**Comment by sknepper** [comment]
Hi @jakub-homola, thanks for the question! The matrices in the LAPACK domain are assumed to be column-major. You're right that we need to add this information to the oneMKL specification. Thanks for finding this!

**Comment by jakub-homola** [comment]
Thanks for the reply.
However, when thinking about it, I think it would be better to add an additional `oneapi::mkl::layout` argument, rather than accepting only column-major matrices. Would it be possible, with respect to backwards compatibility?

**Comment by sknepper** [comment]
Hi @jakub-homola,
When we introduced row major support for the BLAS domain, that was one consideration - to take a parameter that indicated the layout of the matrices (like in CBLAS/LAPACKE). However, we ultimately opted to create separate namespaces as typically an application would use just one layout for the whole application. With namespaces, you don't need to pass an extra layout parameter for every function.

**Comment by sknepper** [comment]
@jakub-homola Thanks again for catching this! I appreciate your interest and thoughtful replies. As we've updated the specification to clarify this, I'd like to ask @mmeterel to close this issue. Please re-open if needed.

And just a note about Intel oneMKL documentation since that was mentioned in the initial report: We note that "Currently, LAPACK DPC++ APIs do not support matrices stored using row major layout." in the Intel® oneAPI Math Kernel Library (oneMKL) - Data Parallel C++ Developer Reference ([link](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/intro-to-onemkl-blas-and-lapack-with-dpcpp.html)). However, we will make this more clear in a future update.  Thanks again!
